### ISSUE TITLE
Error in Python 3.8

### ISSUE THREAD

**Issue by DvoracekD** [votroto/cgt_bandits#1]
Throws exception in Python 3.8. Works only in 3.9.
https://github.com/votroto/cgt_bandits/blob/61ac1fba307e5f1df1e5a8882d04ef66c85d67f8/src/cgt_bandits/nodes.py#L11
`Traceback (most recent call last):
  File "test_poker.py", line 1, in <module>
    from cgt_bandits.nodes import ChanceNode, PersonalNode, TerminalNode
  File "/home/dominik/.local/lib/python3.8/site-packages/cgt_bandits/nodes.py", line 10, in <module>
    class ChanceNode(EFGNode):
  File "/home/dominik/.local/lib/python3.8/site-packages/cgt_bandits/nodes.py", line 11, in ChanceNode
    children: list[EFGNode]
TypeError: 'type' object is not subscriptable
`

**Comment by votroto** [comment]
Confirmed. Thank you!

Would this https://github.com/votroto/cgt_bandits/pull/2#issue-1419406826 fix your issue?

**Comment by DvoracekD** [comment]
Yes exactly.
